version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
        - postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "2022:2022"
    restart: always
    depends_on:
      - db

volumes:
  postgres_volume: