version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 5432:5432
    